

exception Exception

parameter f1 : tt:unit ->
  { }
  unit
  raises Exception
  { true }

let f = fun () ->
  f1 void 

